app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash
from flask_login import UserMixin

db = SQLAlchemy()

team = db.Table(
    'team',
    db.Column('team_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('pokemon_id', db.Integer, db.ForeignKey('caught__pokemon.id'))
)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow())
    team = db.relationship(
        'Caught_Pokemon', secondary=team,
        backref = db.backref('team', lazy='dynamic'),
        lazy='dynamic'
    )

    def __init__(self, first_name, last_name, email, password):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.password = generate_password_hash(password)

    def can_add_pokemon(self):
        return len(list(self.team)) < 5

class Caught_Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    abilities = db.Column(db.String, nullable=False)
    base_experience = db.Column(db.Integer, nullable=False)
    sprites = db.Column(db.String, nullable=False)
    hp = db.Column(db.String, nullable=False)
    attack = db.Column(db.String, nullable=False)
    defense = db.Column(db.String, nullable=False)

    def __init__(self, name, abilities, base_experience, sprites, hp, attack, defense):
        self.name = name
        self.abilities = abilities
        self.base_experience = base_experience
        self.sprites = sprites
        self.hp = hp
        self.attack = attack
        self.defense = defense

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class SearchForm(FlaskForm):
    pokemon_name = StringField('Enter Pokemon:', validators=[DataRequired()])
    search_btn = SubmitField('Search')

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, PasswordField
from wtforms.validators import DataRequired, EqualTo

class SearchForm(FlaskForm):
    pokemon_name = StringField('Enter Pokemon:', validators=[DataRequired()])
    search_btn = SubmitField('Search')

class LoginForm(FlaskForm):
    email = EmailField('Email Address: ', validators=[DataRequired()])
    password = PasswordField('Password: ', validators=[DataRequired()])
    submit_btn = SubmitField('Sign In')

class SignupForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = EmailField('Email Address', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit_btn = SubmitField('Register')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_migrate import Migrate
from .models import db, User

app = Flask(__name__)

app.config.from_object(Config)

login_manager = LoginManager()

db.init_app(app)
migrate = Migrate(app, db)
login_manager.init_app(app)

# login manager settings
login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'warning'

# Importing our blueprints
from app.blueprints.auth import auth
from app.blueprints.main import main

# Registering our blueprints
app.register_blueprint(auth)
app.register_blueprint(main)

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(user_id)

app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='main_templates')

from . import routes

app/blueprints/main/routes.py
from . import main
from flask import request, render_template, redirect, url_for, flash
import requests
from .forms import SearchForm
from app.models import db, Caught_Pokemon, User, team
from flask_login import login_required, current_user


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

@main.route('/attack/<int:user_id>')
@login_required
def attack(user_id):
  user1 = User.query.get(current_user.id)
  user2 = User.query.get(user_id)

  user_1_team = user1.team.all()
  user_2_team = user2.team.all()

  user_1_power = 0
  user_2_power = 0
  for pokemon in user_1_team:
    user_1_power += int(pokemon.attack) + int(pokemon.defense) + int(pokemon.hp)
    
  for pokemon in user_2_team:
    user_2_power += int(pokemon.attack) + int(pokemon.defense) + int(pokemon.hp)

  if user_1_power > user_2_power:
      winner = user1.first_name
  elif user_2_power > user_1_power:
      winner = user2.first_name
  else:
      winner = "No one!"

  return render_template("attack.html", user1=user1, user2=user2, user_1_team=user_1_team, user_2_team=user_2_team, winner=winner, user_1_power=user_1_power, user_2_power=user_2_power)

@main.route('/trainers')
def trainers():
   users = User.query.all()
   
   return render_template("trainers.html", users=users)

@main.route('/view_team')
@login_required
def view_team():
  user = User.query.get(current_user.id)
  
  pokemon_list = user.team.all()
  
  return render_template("team.html", pokemon_list=pokemon_list)


@main.route('/add_to_team/<int:pokemon_id>')
@login_required
def add_to_team(pokemon_id):
  if current_user.can_add_pokemon():
    pokemon = Caught_Pokemon.query.get(pokemon_id)

    current_user.team.append(pokemon)

    db.session.commit()

    flash(f"{pokemon.name} was added to your team!", 'success')
    return redirect(url_for('main.caught_pokemon'))
  else:
    flash(f"Your team is at full capacity!", 'danger')
    return redirect(url_for('main.caught_pokemon'))
      

@main.route('/remove_from_team/<int:pokemon_id>')
@login_required
def remove_from_team(pokemon_id):
  pokemon = Caught_Pokemon.query.get(pokemon_id)

  current_user.team.remove(pokemon)

  db.session.commit()

  flash(f"{pokemon.name} was released from your team!", 'warning')
  return redirect(url_for('main.caught_pokemon'))
  
@main.route('/caught_pokemon')
def caught_pokemon():
   caught_pokemon = Caught_Pokemon.query.all()
   for pokemon in caught_pokemon:
      if pokemon in current_user.team:
         pokemon.inTeam = True
   return render_template('caught_pokemon.html', caught_pokemon=caught_pokemon)

@main.route('/info', methods=['GET', 'POST'])
@login_required
def get_pokemon_info():
    form = SearchForm()
    if request.method == 'POST' and form.validate_on_submit():
      pokemon_name = request.form.get('pokemon_name').lower()
      url = f'https://pokeapi.co/api/v2/pokemon/{pokemon_name}'
      response = requests.get(url)
      if response.ok and len(pokemon_name) > 0:
        data = response.json()
        pokemon = {
            'name': data['name'],
            'abilities': "",
            'base_experience': data['base_experience'],
            'sprites': data['sprites']['front_shiny'],
            'stats': {
                'hp': data['stats'][0]['base_stat'],
                'attack': data['stats'][1]['base_stat'],
                'defense': data['stats'][2]['base_stat']
            }
        }
        for ability in data['abilities']:
            pokemon['abilities'] += " " + ability['ability']['name']
        return render_template('pokemon.html', pokemon=pokemon, form=form)
      return render_template('pokemon.html', form=form)
    else:
      return render_template('pokemon.html', form=form)
    
@main.route('/catch-pokemon/<string:pokemon_name>', methods=['GET', 'POST'])
@login_required
def catch_pokemon(pokemon_name):
    url = f'https://pokeapi.co/api/v2/pokemon/{pokemon_name}'
    response = requests.get(url)
    if response.ok and len(pokemon_name) > 0:
      data = response.json()
      
      name = data['name'].title()
      abilities = ""
      for ability in data['abilities']:
        abilities += " " + ability['ability']['name']
      base_experience = data['base_experience']
      sprites = data['sprites']['front_shiny']
      hp = data['stats'][0]['base_stat']
      attack = data['stats'][1]['base_stat']
      defense = data['stats'][2]['base_stat']

      caught_pokemon = Caught_Pokemon(name, abilities, base_experience, sprites, hp, attack, defense)

      db.session.add(caught_pokemon)
      db.session.commit()

      flash(f'Successfully created caught {name}!', 'success')
      return redirect(url_for('main.get_pokemon_info'))
    flash(f'Pokemon not found!', 'danger')
    return redirect(url_for('main.get_pokemon_info'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap" rel="stylesheet">
    {% block styles %} <link rel="stylesheet" href="../static/global.css">{% endblock %}
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% block content %}
      
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/home.html
{% extends 'base.html '%}
{% block title %}
    Home
{% endblock %}
{% block content %}
{% include './includes/nav.html'%}
<div class="container text-center">
  <div class="row align-items-center" style="height: 500px;">
    <div class="col">
      <h1>Welcome to the Home Page!</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <a class="btn btn-primary" href="{{url_for('get_pokemon_info')}}" role="button">Pokemon Page</a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg mt-0" style="background-color: black;" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('main.home')}}">Thieves-126</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav me-auto">
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{url_for('main.get_pokemon_info')}}">Pokemon Search</a>
        <a class="nav-link" href="{{url_for('main.caught_pokemon')}}">Caught Pokemon</a>
        <a class="nav-link" href="{{url_for('main.view_team')}}">Your Team</a>
        {% endif %}
        {% if current_user.is_authenticated == False %}
        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
        <a class="nav-link" href="{{url_for('auth.signup')}}">Sign Up</a>
        {% endif %}
        <a class="nav-link" style="color: red;" href="{{url_for('main.trainers')}}">Attack Trainers</a>
      </div>
      {% if current_user.is_authenticated %}
      <span class="navbar-text">
        <strong>Hello, {{ current_user.first_name }}</strong>
        <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
      </span>
      {% endif %}
    </div>
  </div>
</nav>

app/templates/pokemon.html
{% extends 'base.html'%}
{% block styles %}
  <link rel="stylesheet" href="../static/login.css">
{% endblock %}
{% block title %}
    Pokemon Info
{% endblock %}

{% block content %}
{% include './includes/nav.html'%}
    <form method="POST" class="w-25 mx-auto mt-5">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.pokemon_name.label(class='form-label') }}
            {{ form.pokemon_name(class='form-control') }}
        </div>
        {{ form.search_btn(class='btn btn-danger') }}
    </form>
    {% if pokemon %}
      <div class="card mx-auto text-bg-light border-danger my-5" style="width: 18rem;">
        <img src={{pokemon.sprites}} class="card-img-top" alt="front shiny">
        <div class="card-body">
          <h3 class="card-title">{{pokemon.name}}</h3>
          <p class="card-text"><strong>Base Experience:</strong> {{pokemon.base_experience}}</p>
          <div class="card-header border-danger">
            Abilities:
          </div>
          <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{pokemon.abilities.ability1}}</li>
            <li class="list-group-item">{{pokemon.abilities.ability2}}</li>
          </ul>
          </div>
          <div class="card-header border-danger">
            Stats:
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
            <li class="list-group-item">HP: {{pokemon.stats.hp}}</li>
            <li class="list-group-item">ATTACK: {{pokemon.stats.attack}}</li>
            <li class="list-group-item">DEFENSE: {{pokemon.stats.defense}}</li>
          </ul>
          </div>
        </div>
      </div>
    {% endif %}
{% endblock %}